language: cpp
compiler:
- gcc
- clang
script: make
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev
notifications:
  email:
    recipients: emil.maskovsky@gmail.com
    on_success: change
    on_failure: always
